# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

container:
  image: sonicdev-microsoft.azurecr.io:443/sonic-slave-buster:latest

steps:
- checkout: self
- script: |
    sudo apt-get install -qq -y \
      qtbase5-dev \
      libdbus-glib-1-2 \
      libdbus-glib-1-dev \
      libpcsclite-dev \
      docbook-to-man \
      docbook-utils \
      aspell-en \
      libhiredis-dev \
      libnl-3-dev \
      libnl-genl-3-dev \
      libnl-route-3-dev \
      libnl-nf-3-dev \
      swig3.0 \
      libpython2.7-dev
  displayName: "Install dependencies"
- task: DownloadPipelineArtifact@2
  inputs:
    source: specific
    project: build
    pipeline: 9
    artifacts: sonic-swss-common
  displayName: "Download sonic swss common deb packages"
- script: |
    pwd
    ls -l /home/vsts/work/1
    ls -l
    ls -l ../
    sudo dpkg -i libswsscommon_1.0.0_amd64.deb
    sudo dpkg -i libswsscommon-dev_1.0.0_amd64.deb
  workingDirectory: $(Pipeline.Workspace)
  displayName: "Install sonic swss Common"
- script: |
    dpkg-buildpackage -us -uc -b
  workingDirectory: sonic-wpa-supplicant
  displayName: "Compile sonic wpa supplicant"
